"""empty message

Revision ID: 3d9b29ecde9c
Revises: 6884e01e2dde
Create Date: 2018-08-16 15:35:47.455886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9b29ecde9c'
down_revision = '6884e01e2dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('claimed_at', sa.String(length=50), nullable=True))
    op.add_column('reservation', sa.Column('returned_at', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'returned_at')
    op.drop_column('reservation', 'claimed_at')
    # ### end Alembic commands ###
