"""empty message

Revision ID: 46e6e4057acd
Revises: 6c1da2086b29
Create Date: 2018-08-19 16:51:27.527299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46e6e4057acd'
down_revision = '6c1da2086b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reservation_ibfk_1', 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('admin', mysql.VARCHAR(length=15), nullable=True))
    op.create_foreign_key('reservation_ibfk_1', 'reservation', 'student', ['studentNumber'], ['studentNumber'])
    # ### end Alembic commands ###
