"""empty message

Revision ID: 65b2ae5ffa2c
Revises: bdb543772e2e
Create Date: 2018-07-02 05:09:32.297630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b2ae5ffa2c'
down_revision = 'bdb543772e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('reservation_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'reservation_date')
    # ### end Alembic commands ###
