"""empty message

Revision ID: 6884e01e2dde
Revises: d4f1f7910a19
Create Date: 2018-08-16 15:26:36.617794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6884e01e2dde'
down_revision = 'd4f1f7910a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'returned_at')
    op.drop_column('student', 'claimed_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('claimed_at', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('student', sa.Column('returned_at', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
