"""empty message

Revision ID: 6c1da2086b29
Revises: 3d9b29ecde9c
Create Date: 2018-08-16 15:48:47.674165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1da2086b29'
down_revision = '3d9b29ecde9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('description', sa.String(length=300), nullable=False))
    op.add_column('reservation', sa.Column('profOrOrg', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'profOrOrg')
    op.drop_column('reservation', 'description')
    # ### end Alembic commands ###
