"""empty message

Revision ID: d4f1f7910a19
Revises: f9df1d986ab0
Create Date: 2018-08-14 22:36:45.076383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f1f7910a19'
down_revision = 'f9df1d986ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment__category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('equipment', sa.Column('categoryId', sa.Integer(), nullable=False))
    op.add_column('student', sa.Column('claimed_at', sa.String(length=50), nullable=True))
    op.add_column('student', sa.Column('returned_at', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'returned_at')
    op.drop_column('student', 'claimed_at')
    op.drop_column('equipment', 'categoryId')
    op.drop_table('equipment__category')
    # ### end Alembic commands ###
