"""empty message

Revision ID: f9df1d986ab0
Revises: aaf74cfe333c
Create Date: 2018-08-12 17:29:48.008855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9df1d986ab0'
down_revision = 'aaf74cfe333c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('contactNumber', sa.String(length=11), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'contactNumber')
    # ### end Alembic commands ###
